# Title : Tensorflow 2.0 Fundamentals
### Author : Raj Shivprakash Poonam Jaiswal
### LinkedIn : https://www.linkedin.com/in/raj-jaiswal-481a33216/
### Twitter: https://twitter.com/home
### Github :https://github.com/Jaiswalraj2908

### 💻: Build Exercise Solutions
### 🌈: Note / conclusion
### 📚: Resources 
### 📌: Session
### 🚀: Exercise

## 🧠PRO TIP : 

 1. Read and Understand the errors present between the code cells.
 2. If in doubt run the code 
 3. Dont hesistate to implement and explore more using resources.

I have intentionally written some codes which will produce error so you can debugg it by yourself and make your self better in tensorflow

## Import Tensorflow 

Download tensorflow : !pip install tensorflow or Use Google collab 

In [1]:
import tensorflow as tf
print("Current tensorflow version running for the project is :",tf.__version__)

Current tensorflow version running for the project is : 2.6.0


### 📚Resources : Tensorflow :  https://www.tensorflow.org/api_docs/python/tf

## Introduction to Tensors

### 📚Resources : Intro to tensors : https://www.tensorflow.org/guide/tensor

# 📌Session 1 : Creating tensors with tf.constant()

In [3]:
scalar = tf.constant(10)
print(scalar) , print("Dimension :",scalar.ndim) 

tf.Tensor(10, shape=(), dtype=int32)
Dimension : 0


(None, None)

In [4]:
vector = tf.constant([10,7])
print(vector) , print("Dimension :",vector.ndim)

tf.Tensor([10  7], shape=(2,), dtype=int32)
Dimension : 1


(None, None)

In [5]:
matrix = tf.constant([[10,7],
                     [11,15]])
print(matrix) ,print("Dimension :",matrix.ndim)

tf.Tensor(
[[10  7]
 [11 15]], shape=(2, 2), dtype=int32)
Dimension : 2


(None, None)

In [6]:
tensor = tf.constant([[[10,7],
                      [11.2,15],
                      [20,55]],
                     [[88,95],
                     [36.5,42],
                     [23,69]]] ,dtype=tf.float16)
print(tensor) ,print("Dimension :",tensor.ndim)

tf.Tensor(
[[[10.   7. ]
  [11.2 15. ]
  [20.  55. ]]

 [[88.  95. ]
  [36.5 42. ]
  [23.  69. ]]], shape=(2, 3, 2), dtype=float16)
Dimension : 3


(None, None)

#  📌Session 2 : Creating tensors with tf.Variable()

In [8]:
changable_tensor = tf.Variable([10,7])
unchagable_tensor = tf.constant([10,7])

In [9]:
print("Changable tensor :",changable_tensor)

Changable tensor : <tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7])>


In [10]:
print("Unchangeble Tensor :",unchagable_tensor)

Unchangeble Tensor : tf.Tensor([10  7], shape=(2,), dtype=int32)


### new item assign to changable and unchangeble tensor

In [12]:
changable_tensor_2 = changable_tensor[0].assign(7)
print(changable_tensor_2)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([7, 7])>


In [13]:
unchageble_tensor_2 = unchagable_tensor[0].assign(7)
print(unchageble_tensor_2)

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

### 🌈 Conclusion : tf.constant() has no flexibility to change its elements while tf.Variable () has .

# 📌Session 3 : Creating random tensors using tensorflow

These random numbers are pseudo random numbers

In [14]:
random_tensor = tf.random.normal(shape = (3,2))
print(random_tensor) , print("Dimension :",random_tensor.ndim)

tf.Tensor(
[[-1.9479886   1.1856734 ]
 [ 0.01003122  0.22352912]
 [-0.06907108 -1.0121607 ]], shape=(3, 2), dtype=float32)
Dimension : 2


(None, None)

In [15]:
tf.random.set_seed(42)                             # set seed for reproducibility

random_tensor_1 = tf.random.normal(shape = (3,2))
print(random_tensor_1) ,print("Dimension:",random_tensor_1.ndim)

tf.Tensor(
[[ 0.3274685 -0.8426258]
 [ 0.3194337 -1.4075519]
 [-2.3880599 -1.0392479]], shape=(3, 2), dtype=float32)
Dimension: 2


(None, None)

In [16]:
random_tensor == random_tensor_1 

<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[False, False],
       [False, False],
       [False, False]])>

### since the elements in random tensor above continoulsly varying both are unequal 

In [17]:
tf.random.set_seed(42)

random_tensor_2 = tf.random.normal(shape = (3,2))
print(random_tensor_2) ,print("Dimension ",random_tensor_2.ndim)

tf.Tensor(
[[ 0.3274685 -0.8426258]
 [ 0.3194337 -1.4075519]
 [-2.3880599 -1.0392479]], shape=(3, 2), dtype=float32)
Dimension  2


(None, None)

### since set seed (42) is used , despite of running code cells considerable amount of time it still shows the same output

In [18]:

random_tensor_1 == random_tensor_2


<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[ True,  True],
       [ True,  True],
       [ True,  True]])>

### 🌈 conclusion : Since set seed(42) is present , both displays same output 

In [19]:
tf.random.set_seed(42)

random_tensor_3 = tf.random.uniform(shape = (3,2))
print(random_tensor_3) ,print("Dimension : ",random_tensor_3.ndim)

tf.Tensor(
[[0.6645621  0.44100678]
 [0.3528825  0.46448255]
 [0.03366041 0.68467236]], shape=(3, 2), dtype=float32)
Dimension :  2


(None, None)

In [20]:
random_tensor_2 == random_tensor_3 


<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[False, False],
       [False, False],
       [False, False]])>

### 🌈 Conclusion : Although they both have same shape , same dimesnion , set seed(42)  but still they both are distributed randomly in different way normal and uniform.


### Shuffling the order of tensors . In order to keep balnce between the distribution of targets in dataset . Stratify concept 

In [22]:
not_shuffle = tf.constant([[10,7],
                          [3,2],
                          [15,20]])
print(not_shuffle) ,print("Dimension :",not_shuffle.ndim)

tf.Tensor(
[[10  7]
 [ 3  2]
 [15 20]], shape=(3, 2), dtype=int32)
Dimension : 2


(None, None)

 ###  shuffle by rows

In [23]:
shuffle_tensor = tf.random.shuffle(not_shuffle)
print(shuffle_tensor) ,print("Dimension : ",shuffle_tensor.ndim)

tf.Tensor(
[[15 20]
 [10  7]
 [ 3  2]], shape=(3, 2), dtype=int32)
Dimension :  2


(None, None)

### Example of local / operational level set seed

In [24]:
shuffle_tensor = tf.random.shuffle(not_shuffle , seed = 42)
print(shuffle_tensor) ,print("Dimension : ",shuffle_tensor.ndim)

tf.Tensor(
[[10  7]
 [ 3  2]
 [15 20]], shape=(3, 2), dtype=int32)
Dimension :  2


(None, None)

### Example of global level set seed

In [25]:

tf.random.set_seed(42)

shuffle_tensor = tf.random.shuffle(not_shuffle)
print(shuffle_tensor) ,print("Dimension : ",shuffle_tensor.ndim)

tf.Tensor(
[[ 3  2]
 [15 20]
 [10  7]], shape=(3, 2), dtype=int32)
Dimension :  2


(None, None)

# 📌Session 4 : NumPy arrays turn into tensors

In [26]:
import numpy as np

In [27]:
tf.ones(shape=(10,5))

<tf.Tensor: shape=(10, 5), dtype=float32, numpy=
array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]], dtype=float32)>

In [28]:
tf.zeros(shape=(5,3))

<tf.Tensor: shape=(5, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

### can convert numpy arrays into a tensors

In [30]:
numpy_A = np.arange(start = 1 , stop =25 ,dtype = np.int32)
numpy_A 

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [31]:
print(type(numpy_A))

<class 'numpy.ndarray'>


In [32]:
np_to_tf = tf.constant(numpy_A)
np_to_tf

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])>

In [33]:
np_to_tf_1 = tf.constant(numpy_A , shape = (2,3,4))
np_to_tf_1

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])>

In [34]:
2*3*4

24

In [35]:
np_to_tf_2 = tf.constant(numpy_A , shape = ( 4,2,3))
np_to_tf_2

<tf.Tensor: shape=(4, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24]]])>

In [36]:
4*2*3

24

In [37]:
np_to_tf_3 = tf.constant(numpy_A , shape = ( 4,4,2))
np_to_tf_3

TypeError: Eager execution of tf.constant with unsupported shape (value has 24 elements, shape is (4, 4, 2) with 32 elements).

In [38]:
4*4*2

32

In [39]:
len(np_to_tf_1) # 2 sub division of arrays

2

In [40]:
len(np_to_tf_2) # 4 sub division of arrays

4

In [41]:
len(np_to_tf_1) == len(np_to_tf_2)

False

In [42]:
tf.size(np_to_tf_1) == tf.size(np_to_tf_2)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

### 🌈 Length provides the length of array  which is the total space allocatd during  initilization whereas size provides the total no. of elements present in the array


# 📌Session 5 : Tensors attributes

In [44]:
tensor = tf.constant([[[10,7],
                      [11.2,15],
                      [20,55]],
                     [[88,95],
                     [36.5,42],
                     [23,69]],
                     [[22,43],
                     [70,99],
                     [10,90]]] )
print(tensor) 

tf.Tensor(
[[[10.   7. ]
  [11.2 15. ]
  [20.  55. ]]

 [[88.  95. ]
  [36.5 42. ]
  [23.  69. ]]

 [[22.  43. ]
  [70.  99. ]
  [10.  90. ]]], shape=(3, 3, 2), dtype=float32)


In [45]:
# shape
print("Shape :" ,tf.shape(tensor))

# rank
print("rank :",tf.rank(tensor))

# size
print("Size :",tf.size(tensor))

#dimension
print("Dimension :",tensor.ndim)

# datatype
print("Datatype:" , tensor.dtype)

Shape : tf.Tensor([3 3 2], shape=(3,), dtype=int32)
rank : tf.Tensor(3, shape=(), dtype=int32)
Size : tf.Tensor(18, shape=(), dtype=int32)
Dimension : 3
Datatype: <dtype: 'float32'>


In [46]:
# shape
print("Shape :" ,tf.shape(tensor).numpy())

# rank
print("rank :",tf.rank(tensor).numpy())

# size
print("Size :",tf.size(tensor).numpy())

#dimension
print("Dimension :",tensor.ndim)

# datatype
print("Datatype:" , tensor.dtype)

Shape : [3 3 2]
rank : 3
Size : 18
Dimension : 3
Datatype: <dtype: 'float32'>


# 📌Session 6 : Indexing and expanding tensors

In [47]:
tensor

<tf.Tensor: shape=(3, 3, 2), dtype=float32, numpy=
array([[[10. ,  7. ],
        [11.2, 15. ],
        [20. , 55. ]],

       [[88. , 95. ],
        [36.5, 42. ],
        [23. , 69. ]],

       [[22. , 43. ],
        [70. , 99. ],
        [10. , 90. ]]], dtype=float32)>

In [48]:
tensor[:,:3,:1]

<tf.Tensor: shape=(3, 3, 1), dtype=float32, numpy=
array([[[10. ],
        [11.2],
        [20. ]],

       [[88. ],
        [36.5],
        [23. ]],

       [[22. ],
        [70. ],
        [10. ]]], dtype=float32)>

In [49]:
tensor[:2,:1,:2]

<tf.Tensor: shape=(2, 1, 2), dtype=float32, numpy=
array([[[10.,  7.]],

       [[88., 95.]]], dtype=float32)>

In [50]:
tensor[:1,:3,:2]

<tf.Tensor: shape=(1, 3, 2), dtype=float32, numpy=
array([[[10. ,  7. ],
        [11.2, 15. ],
        [20. , 55. ]]], dtype=float32)>

In [51]:
tensor[:,:,:]

<tf.Tensor: shape=(3, 3, 2), dtype=float32, numpy=
array([[[10. ,  7. ],
        [11.2, 15. ],
        [20. , 55. ]],

       [[88. , 95. ],
        [36.5, 42. ],
        [23. , 69. ]],

       [[22. , 43. ],
        [70. , 99. ],
        [10. , 90. ]]], dtype=float32)>

In [52]:
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [11, 15]])>

In [53]:
matrix[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 15])>

In [54]:
matrix.shape

TensorShape([2, 2])

In [55]:
add_cols_matrix = matrix[...,tf.newaxis]
add_cols_matrix

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[11],
        [15]]])>

In [56]:
add_cols_matrix.shape

TensorShape([2, 2, 1])

In [57]:
expand_dims_0 = tf.expand_dims(matrix ,axis = 0)
print(expand_dims_0)

tf.Tensor(
[[[10  7]
  [11 15]]], shape=(1, 2, 2), dtype=int32)


In [58]:
expand_dims_1 = tf.expand_dims(matrix,axis =1)
print(expand_dims_1)

tf.Tensor(
[[[10  7]]

 [[11 15]]], shape=(2, 1, 2), dtype=int32)


In [59]:
expand_dims_2 = tf.expand_dims(matrix ,axis = 2)
print(expand_dims_2)

tf.Tensor(
[[[10]
  [ 7]]

 [[11]
  [15]]], shape=(2, 2, 1), dtype=int32)


In [60]:
expand_dims_3 = tf.expand_dims(matrix ,axis = 3)
print(expand_dims_3)

InvalidArgumentError: Tried to expand dim index 3 for tensor with 2 dimensions. [Op:ExpandDims]

# 📌Session 7 :Tensors Manipulation 

### 📚Resources : tf.math : https://www.tensorflow.org/api_docs/python/tf/math

In [63]:
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [11, 15]])>

In [64]:
matrix + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [21, 25]])>

In [65]:
matrix - 15

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[-5, -8],
       [-4,  0]])>

In [66]:
matrix * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [110, 150]])>

In [67]:
matrix / 10  # return quotient

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[1. , 0.7],
       [1.1, 1.5]])>

In [68]:
matrix % 10 # reurn remainder 

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[0, 7],
       [1, 5]])>

In [69]:
matrix ** 2       # power

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  49],
       [121, 225]])>

In [70]:
tf.math.sqrt(matrix) 

InvalidArgumentError: Value for attr 'T' of int32 is not in the list of allowed values: bfloat16, half, float, double, complex64, complex128
	; NodeDef: {{node Sqrt}}; Op<name=Sqrt; signature=x:T -> y:T; attr=T:type,allowed=[DT_BFLOAT16, DT_HALF, DT_FLOAT, DT_DOUBLE, DT_COMPLEX64, DT_COMPLEX128]> [Op:Sqrt]

In [71]:
matrix_1  = tf.cast(matrix ,dtype = tf.float32)

In [72]:
tf.math.sqrt(matrix_1) # datatype should not be an int

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[3.1622777, 2.6457512],
       [3.3166249, 3.8729832]], dtype=float32)>

In [73]:
tf.math.sqrt((matrix/10))    

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[1.        , 0.83666003],
       [1.04880885, 1.22474487]])>

# 📌Session 8 : Matrix Multplication with tensors 

### 📚Resources : Matrix Multiplication : https://www.mathsisfun.com/algebra/matrix-multiplying.html

#### Play with Matrix Multiplcation : http://matrixmultiplication.xyz/

In [76]:
mat_mul_tensor_1 = tf.constant([[10,7,30],
                               [21,36,9],
                               [88,74,95]])
print(mat_mul_tensor_1) , print("shape:",tf.shape(mat_mul_tensor_1).numpy()) , print("Dimension :" ,mat_mul_tensor_1.ndim)

tf.Tensor(
[[10  7 30]
 [21 36  9]
 [88 74 95]], shape=(3, 3), dtype=int32)
shape: [3 3]
Dimension : 2


(None, None, None)

In [77]:
mat_mul_tensor_2 = tf.constant([[8,19,20],
                               [23,6,98],
                               [11,20,39]])
print(mat_mul_tensor_2) ,print("shape" ,tf.shape(mat_mul_tensor_2).numpy()) , print("Dimension : " , mat_mul_tensor_2.ndim)

tf.Tensor(
[[ 8 19 20]
 [23  6 98]
 [11 20 39]], shape=(3, 3), dtype=int32)
shape [3 3]
Dimension :  2


(None, None, None)

In [78]:
tf.matmul(a = mat_mul_tensor_1 , b = mat_mul_tensor_2) # same  result obtained as tf.tensordot

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[  571,   832,  2056],
       [ 1095,   795,  4299],
       [ 3451,  4016, 12717]])>

### 📚Resources : tensordot : https://docs.w3cub.com/tensorflow~1.15/tensordot

In [80]:
tf.tensordot(a = mat_mul_tensor_1 , b =mat_mul_tensor_2 , axes = 0)

<tf.Tensor: shape=(3, 3, 3, 3), dtype=int32, numpy=
array([[[[  80,  190,  200],
         [ 230,   60,  980],
         [ 110,  200,  390]],

        [[  56,  133,  140],
         [ 161,   42,  686],
         [  77,  140,  273]],

        [[ 240,  570,  600],
         [ 690,  180, 2940],
         [ 330,  600, 1170]]],


       [[[ 168,  399,  420],
         [ 483,  126, 2058],
         [ 231,  420,  819]],

        [[ 288,  684,  720],
         [ 828,  216, 3528],
         [ 396,  720, 1404]],

        [[  72,  171,  180],
         [ 207,   54,  882],
         [  99,  180,  351]]],


       [[[ 704, 1672, 1760],
         [2024,  528, 8624],
         [ 968, 1760, 3432]],

        [[ 592, 1406, 1480],
         [1702,  444, 7252],
         [ 814, 1480, 2886]],

        [[ 760, 1805, 1900],
         [2185,  570, 9310],
         [1045, 1900, 3705]]]])>

In [81]:
tf.tensordot(a = mat_mul_tensor_1 , b =mat_mul_tensor_2 , axes = 1) # same  result obtained as tf.matmul

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[  571,   832,  2056],
       [ 1095,   795,  4299],
       [ 3451,  4016, 12717]])>

In [82]:
tf.tensordot(a = mat_mul_tensor_1 , b =mat_mul_tensor_2 , axes = 2)

<tf.Tensor: shape=(), dtype=int32, numpy=8547>

### Here axes = 2 is correct values . since dot product never gives a matrix as a output. It always provide a single value

In [84]:
tf.tensordot(a = mat_mul_tensor_1 , b =mat_mul_tensor_2 , axes = 3)


ValueError: 'axes' must not be larger than the number of dimensions of tensor tf.Tensor(
[[10  7 30]
 [21 36  9]
 [88 74 95]], shape=(3, 3), dtype=int32).

### Error ??? Why ? 'axes' must not be larger than the number of dimensions of tensor... Here the rank or dimension was 2  

In [85]:
tensor

<tf.Tensor: shape=(3, 3, 2), dtype=float32, numpy=
array([[[10. ,  7. ],
        [11.2, 15. ],
        [20. , 55. ]],

       [[88. , 95. ],
        [36.5, 42. ],
        [23. , 69. ]],

       [[22. , 43. ],
        [70. , 99. ],
        [10. , 90. ]]], dtype=float32)>

In [ ]:
tf.tensordot(a = tensor , b= tensor , axes=3)


### where is Error ? Here Rank or dimesnion is 3 

## 🌈 conclusion : axes values = rank of a matrix

In [125]:
mat_mul_tensor_1

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[10,  7, 30],
       [21, 36,  9],
       [88, 74, 95]])>

In [126]:
tf.transpose(mat_mul_tensor_1)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[10, 21, 88],
       [ 7, 36, 74],
       [30,  9, 95]])>

## 🌈 concluion : Colms turn into rows or vice versa

# 📌Sessison 9 : Tensor aggregation 

In [74]:
tensor

<tf.Tensor: shape=(3, 3, 2), dtype=float32, numpy=
array([[[10. ,  7. ],
        [11.2, 15. ],
        [20. , 55. ]],

       [[88. , 95. ],
        [36.5, 42. ],
        [23. , 69. ]],

       [[22. , 43. ],
        [70. , 99. ],
        [10. , 90. ]]], dtype=float32)>

In [127]:
# mean

print("Mean :" ,tf.reduce_mean(tensor).numpy())

# max

print("Max:",tf.reduce_max(tensor).numpy())

# min

print("Min:",tf.reduce_min(tensor).numpy())

# std

print("Std dev:",tf.math.reduce_std(tensor).numpy())

# var

print("variance:",tf.math.reduce_variance(tensor).numpy())



Mean : 44.761112
Max: 99.0
Min: 7.0
Std dev: 31.841328
variance: 1013.8701


In [132]:
tf.random.set_seed(42)

mat = tf.random.uniform(shape= [50])

In [133]:
mat

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [135]:
# argmin (index / position)

print("argmin index :" , tf.argmin(mat).numpy())

#argmax (index / position)

print("Argmax index:" , tf.argmax(mat).numpy())

argmin index : 16
Argmax index: 42


In [137]:
mat[tf.argmin(mat)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

In [139]:
mat[tf.argmax(mat)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

# 📌Session 10 : Squeezing tensors 

### 📚Resource : https://www.tensorflow.org/api_docs/python/tf/squeeze?hl=ja

In [114]:
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [11, 15]])>

In [118]:
expanded_1 = tf.expand_dims(input = matrix , axis = 2)
print(expanded_1)

tf.Tensor(
[[[10]
  [ 7]]

 [[11]
  [15]]], shape=(2, 2, 1), dtype=int32)


In [119]:
squeezed_1 = tf.squeeze(input = expanded_1)

In [120]:
print(squeezed_1) , print("shape of squeezed :" , tf.shape(squeezed).numpy())

tf.Tensor(
[[10  7]
 [11 15]], shape=(2, 2), dtype=int32)
shape of squeezed : [2 2]


(None, None)

In [121]:
expanded_2 = tf.expand_dims(input=matrix , axis = 1)

In [122]:
print(expanded_2)

tf.Tensor(
[[[10  7]]

 [[11 15]]], shape=(2, 1, 2), dtype=int32)


In [123]:
squeezed_2 = tf.squeeze(input = expanded_2)

In [124]:
print(squeezed_2)

tf.Tensor(
[[10  7]
 [11 15]], shape=(2, 2), dtype=int32)


# 📌Session 11 : One hot encoding tensorflow

In [90]:
indices = [1,2,3,4]
print(indices)

[1, 2, 3, 4]


In [99]:
tf.one_hot(indices=indices ,depth = 5)

<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
array([[0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]], dtype=float32)>

In [100]:
list = ["lion", "tiger" ,"rhino","fox"]
print(list)

['lion', 'tiger', 'rhino', 'fox']


In [101]:
tf.one_hot(indices=list , depth = 5)

InvalidArgumentError: Value for attr 'TI' of string is not in the list of allowed values: uint8, int32, int64
	; NodeDef: {{node OneHot}}; Op<name=OneHot; signature=indices:TI, depth:int32, on_value:T, off_value:T -> output:T; attr=axis:int,default=-1; attr=T:type; attr=TI:type,default=DT_INT64,allowed=[DT_UINT8, DT_INT32, DT_INT64]> [Op:OneHot]

###  Congratulations ..You are 🐐 of Tensorflow 2.0 fundamentals now.. I apprepreciate your efforts and Learning 

## HAPPY TENSORFLOW 2.0 LEARNING