# Title : Numpy for Machine Learning 
### Author : Raj Shivprakash Poonam Jaiswal
### LinkedIn : https://www.linkedin.com/in/raj-jaiswal-481a33216/
### Twitter: https://twitter.com/home
### Github :https://github.com/Jaiswalraj2908

### 💻: Build Exercise Solutions
### 🌈: Note 
### 📚: Resources 
### 📌: Session
### 🚀: Exercise

# Why Numpy ?


 Numpy is one of the most commonly used packages for scientific computing in Python. It provides a multidimensional array object, as well as variations such as masks and matrices, which can be used for various math operations.

#### 📚Resources : Numpy vs Lists :- https://stackoverflow.com/questions/993984/what-are-the-advantages-of-numpy-over-regular-python-lists

### 🌍Import Numpy 

In [1]:
import numpy as np

### 🌋 When you will complete this Numpy notebook you will understand this  2 cells of code

In [2]:
np.random.seed(42)

massive_aaray = np.random.random(100000)
massive_aaray.size

100000

In [3]:
print("Python sum function used in lists ( time in mili seconds)")
%timeit sum(massive_aaray)

print("--------------------------------------------------------------------")

print("Numpy sum function used in array ( time in micro seconds)")
%timeit np.sum(massive_aaray)

Python sum function used in lists ( time in mili seconds)
12.3 ms ± 198 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
--------------------------------------------------------------------
Numpy sum function used in array ( time in micro seconds)
37.1 µs ± 185 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


## 📌Session 1 : Numpy Datatypes and Attributes

#### Create a Numpy array where the universal  type is always ndarray which is very flexible to manipulate or perform mathematical operations.


In [4]:
array1 = np.array([10,7,19])

In [5]:
print(array1)

[10  7 19]


From above output result we can observe a list of 3 elements(size) which is having 1 row and 3 coloumns (shape) and its an int (datatype) also its seems its is 1-D (ndim) with ndarray (type).

Lets Verify our observation using some Numpy attributes.

In [6]:
print("Size :",array1.size)
print("Shape :" , array1.shape) # since shape is rows x colms , you can see bit  change in 1-D shape
print("Data type :",array1.dtype)
print("Dimension of array:" , array1.ndim)
print("Type of array :" ,type(array1))

Size : 3
Shape : (3,)
Data type : int32
Dimension of array: 1
Type of array : <class 'numpy.ndarray'>


In [7]:
array2 = np.array([[10,7,19],
                  [1,2,3.05,]])

In [8]:
print(array2)

[[10.    7.   19.  ]
 [ 1.    2.    3.05]]


From above output result we can observe a list ( Matrix ) of 6 elements(size) which is having 2 row and 3 coloumns (shape) and its an float (datatype) also its seems its is 2-D (ndim) with ndarray (type).

Lets Verify our observation using some Numpy attributes.

In [9]:
print("Size :",array2.size)
print("Shape :" , array2.shape) 
print("Data type :",array2.dtype)
print("Dimension of array:" , array2.ndim)
print("Type of array :" ,type(array2))

Size : 6
Shape : (2, 3)
Data type : float64
Dimension of array: 2
Type of array : <class 'numpy.ndarray'>


In [10]:
array3 = np.array([[[10,7,19],
                   [1,2,3],
                   [20,55,90]],
                   [[99,88,77],
                   [37,54,29],
                   [23,59,62]]])

In [11]:
print(array3)

[[[10  7 19]
  [ 1  2  3]
  [20 55 90]]

 [[99 88 77]
  [37 54 29]
  [23 59 62]]]


From above output result we can observe a list ( Matrix ) of 18 elements(size) which is having 3 row and 3 coloumns (shape) in each matrix of matrix  and its an int (datatype) also its seems its is 3-D (ndim) with ndarray (type).

Lets Verify our observation using some Numpy attributes.

In [12]:
print("Size :",array3.size)
print("Shape :" , array3.shape) 
print("Data type :",array3.dtype)
print("Dimension of array:" , array3.ndim)
print("Type of array :" ,type(array3))

Size : 18
Shape : (2, 3, 3)
Data type : int32
Dimension of array: 3
Type of array : <class 'numpy.ndarray'>


### 🚀 I encourage you to make 4 Dimension of array 

## 📌Session 2 : Creating Numpy arrays

In an Early stage we have created numpy by own BUT BUT we have some numpy functions to create arrays by defining shape ,size , dimesnions etc .

LETS check it out !!!!

**😎PRO TIP : Press Shift + Tab to know the functions Parameters**

In [13]:
ones = np.ones(shape = (1,3))

In [14]:
print(ones)

[[1. 1. 1.]]


In [15]:
print("Size :",ones.size)
print("Shape :" ,ones.shape) 
print("Data type :",ones.dtype)
print("Dimension of array:" , ones.ndim)
print("Type of array :" ,type(ones))

Size : 3
Shape : (1, 3)
Data type : float64
Dimension of array: 2
Type of array : <class 'numpy.ndarray'>


In [16]:
zeros = np.zeros(shape = (3,3))

In [17]:
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [18]:
print("Size :",zeros.size)
print("Shape :" ,zeros.shape) 
print("Data type :",zeros.dtype)
print("Dimension of array:" , zeros.ndim)
print("Type of array :" ,type(zeros))

Size : 9
Shape : (3, 3)
Data type : float64
Dimension of array: 2
Type of array : <class 'numpy.ndarray'>


In [19]:
arange = np.arange(start = 0 ,stop = 10 ,step = 2)

In [20]:
print(arange)

[0 2 4 6 8]


In [21]:
print("Size :",arange.size)
print("Shape :" ,arange.shape) 
print("Data type :",arange.dtype)
print("Dimension of array:" , arange.ndim)
print("Type of array :" ,type(arange))

Size : 5
Shape : (5,)
Data type : int32
Dimension of array: 1
Type of array : <class 'numpy.ndarray'>


In [22]:
random_int = np.random.randint(low = 0 ,high = 10 ,size =(5,5))

In [23]:
print(random_int)

[[1 7 8 0 5]
 [5 6 5 0 5]
 [3 0 9 5 2]
 [3 7 7 2 3]
 [2 7 2 9 2]]


In [24]:
print("Size :",arange.size)
print("Shape :" ,arange.shape) 
print("Data type :",arange.dtype)
print("Dimension of array:" , arange.ndim)
print("Type of array :" ,type(arange))

Size : 5
Shape : (5,)
Data type : int32
Dimension of array: 1
Type of array : <class 'numpy.ndarray'>


In [25]:
random_rand = np.random.rand(2,5,5)

In [26]:
print(random_rand)

[[[0.53519364 0.16873659 0.77563843 0.26595915 0.61502457]
  [0.89940004 0.03858561 0.38753394 0.13491776 0.90865771]
  [0.36007744 0.21334093 0.67647658 0.54319279 0.81693668]
  [0.75306816 0.97466985 0.09053231 0.08027277 0.9073607 ]
  [0.95573222 0.40663435 0.45586983 0.36869829 0.77768688]]

 [[0.77078662 0.22041966 0.38389413 0.21243668 0.04662415]
  [0.05612146 0.14682312 0.02988204 0.42317521 0.06401951]
  [0.84741139 0.71208198 0.78364284 0.61748012 0.66387733]
  [0.11341003 0.05816765 0.98921411 0.37294936 0.05127002]
  [0.15964599 0.874206   0.20579868 0.46704207 0.66747419]]]


In [27]:
print("Size :",random_rand.size)
print("Shape :" ,random_rand.shape) 
print("Data type :",random_rand.dtype)
print("Dimension of array:" , random_rand.ndim)
print("Type of array :" ,type(random_rand))

Size : 50
Shape : (2, 5, 5)
Data type : float64
Dimension of array: 3
Type of array : <class 'numpy.ndarray'>


### 🚀 I encourage you to tweak the parameters of functions and observe those  array 

## 📌Session 3 : Numpy Random Seed

#### 📚 Resources : Random Seed :- https://www.sharpsightlabs.com/blog/numpy-random-seed/

# What is Pseudo Random Numbers ? 


A set of values or elements that is statistically random, but it is derived from a known starting point and is typically repeated over and over. ... It is called "pseudo" random, because the algorithm can repeat the sequence, and the numbers are thus not entirely random.



In [28]:
Random_int_01 = np.random.randint(low = 0 , high = 100 ,size = (10,10))

In [29]:
print(Random_int_01)

[[45 88 99  6 14 92 71 36 73 73]
 [59 49 12 18 48 22 54 14 80  9]
 [55 62 56 45 32 55 17 67 58  3]
 [14 30  1 75 61 32 45 49 19 65]
 [64 83 23 13 48 40 28 20 31 58]
 [52 86 92 77 62 70 22 80 33 95]
 [36  4 41 83 71 71 87 24 45 26]
 [95  6 59 11  6 44  7  3 27 45]
 [60 79 39 33 26 25 10  0 20 31]
 [74 86 59 67  1 83 91 53  8 68]]


In [30]:
np.random.seed(42)


Random_int_02 = np.random.randint(low = 0 , high = 100 ,size = (10,10))

In [31]:
print(Random_int_02)

[[51 92 14 71 60 20 82 86 74 74]
 [87 99 23  2 21 52  1 87 29 37]
 [ 1 63 59 20 32 75 57 21 88 48]
 [90 58 41 91 59 79 14 61 61 46]
 [61 50 54 63  2 50  6 20 72 38]
 [17  3 88 59 13  8 89 52  1 83]
 [91 59 70 43  7 46 34 77 80 35]
 [49  3  1  5 53  3 53 92 62 17]
 [89 43 33 73 61 99 13 94 47 14]
 [71 77 86 61 39 84 79 81 52 23]]


#### 🚀 I encourage you to find the difference between both the random integers array that what is exactly happening with the set of numbers

## 📌Session 4 : Viewing Array and Matrices

#### 📚 Resources : Basic Slicing and indexing : - https://www.geeksforgeeks.org/indexing-in-numpy/

#### 😎 **In Python index always starts with 0 and ends with n-1 . I encourage you to click above link or go throughthe python notebook in my Machine Learning Notebook**

#### Index [ rows_start : rows_end , cols_start : cols_end ]

In [32]:
print(array1)

[10  7 19]


In [33]:
print(array1.shape)

(3,)


In [34]:
print(array1[0]) ,print(array1[1]) ,print(array1[2]) 

10
7
19


(None, None, None)

In [35]:
print(array1[-1]) , print(array1[-2]) ,print(array1[-3])

19
7
10


(None, None, None)

In [36]:
print(array2)

[[10.    7.   19.  ]
 [ 1.    2.    3.05]]


In [37]:
print(array2.shape)

(2, 3)


In [38]:
print(array2[0:1 ,0:2])

[[10.  7.]]


Above you can observe we  extract two columns of first row because 0:1 force to extract 0th row and 0:2 force to extract 0th and 1th  cols excluding 2nd

In [39]:
print(array3)

[[[10  7 19]
  [ 1  2  3]
  [20 55 90]]

 [[99 88 77]
  [37 54 29]
  [23 59 62]]]


In [40]:
print(array3.shape)

(2, 3, 3)


In [41]:
print(array3[:,:2,:2])

[[[10  7]
  [ 1  2]]

 [[99 88]
  [37 54]]]


#### Write your own observation in your words in your notebook after implementing the array3 cell.

### 🚀 Exercise :  I encourage you to create an array of random integers with shape = ( 2,3,4,5) with low = 0 and high = 100  with seed (42)

1. Find Unique Values
2. Extract 2 cols from each array/ matrix
3. Extract 2 rows from each array / matrix
4. Find Dimension ,shape ,size ,datatype of matrix 

### 💻 Build and excerise with Solutions ( Give A try to yourself )

In [42]:
np.random.seed(42)

excercise = np.random.randint(low = 0 , high = 100 ,size=(2,3,4,5))

In [43]:
print(excercise)

[[[[51 92 14 71 60]
   [20 82 86 74 74]
   [87 99 23  2 21]
   [52  1 87 29 37]]

  [[ 1 63 59 20 32]
   [75 57 21 88 48]
   [90 58 41 91 59]
   [79 14 61 61 46]]

  [[61 50 54 63  2]
   [50  6 20 72 38]
   [17  3 88 59 13]
   [ 8 89 52  1 83]]]


 [[[91 59 70 43  7]
   [46 34 77 80 35]
   [49  3  1  5 53]
   [ 3 53 92 62 17]]

  [[89 43 33 73 61]
   [99 13 94 47 14]
   [71 77 86 61 39]
   [84 79 81 52 23]]

  [[25 88 59 40 28]
   [14 44 64 88 70]
   [ 8 87  0  7 87]
   [62 10 80  7 34]]]]


In [44]:
# 1.Find Unique Values

print(np.unique(excercise))

[ 0  1  2  3  5  6  7  8 10 13 14 17 20 21 23 25 28 29 32 33 34 35 37 38
 39 40 41 43 44 46 47 48 49 50 51 52 53 54 57 58 59 60 61 62 63 64 70 71
 72 73 74 75 77 79 80 81 82 83 84 86 87 88 89 90 91 92 94 99]


In [45]:
# 2. Extract 2 cols from each array/ matrix

print(excercise[:,:,:,:2])

[[[[51 92]
   [20 82]
   [87 99]
   [52  1]]

  [[ 1 63]
   [75 57]
   [90 58]
   [79 14]]

  [[61 50]
   [50  6]
   [17  3]
   [ 8 89]]]


 [[[91 59]
   [46 34]
   [49  3]
   [ 3 53]]

  [[89 43]
   [99 13]
   [71 77]
   [84 79]]

  [[25 88]
   [14 44]
   [ 8 87]
   [62 10]]]]


In [46]:
# 3. Extract 2 rows from each array / matrix

print(excercise[:,:,:2,:])

[[[[51 92 14 71 60]
   [20 82 86 74 74]]

  [[ 1 63 59 20 32]
   [75 57 21 88 48]]

  [[61 50 54 63  2]
   [50  6 20 72 38]]]


 [[[91 59 70 43  7]
   [46 34 77 80 35]]

  [[89 43 33 73 61]
   [99 13 94 47 14]]

  [[25 88 59 40 28]
   [14 44 64 88 70]]]]


In [47]:
# 4. Find Dimension ,shape ,size ,datatype of matrix

print("Dimension:",excercise.ndim)
print("Shape :",excercise.shape)
print("Size :" , excercise.size)
print("Datatype :" ,excercise.dtype)
print("Type of array :" ,type(excercise))

Dimension: 4
Shape : (2, 3, 4, 5)
Size : 120
Datatype : int32
Type of array : <class 'numpy.ndarray'>


###  👽I hope you have done this exercise by your own so congratulate for your progress and if not dont worry here is the solution above , Go and Practise .

## 📌Session 5 : Manipulating Arrays

#### 📚 Resources : Manipulating Arrays :- https://numpy.org/doc/stable/reference/routines.array-manipulation.html 


## Arthimatic

In [48]:
print(array1) ,print("Shape :" ,array1.shape)

[10  7 19]
Shape : (3,)


(None, None)

In [49]:
Ones = np.ones(shape = (1,3))
print(Ones) ,print("Shape:",Ones.shape)

[[1. 1. 1.]]
Shape: (1, 3)


(None, None)

In [50]:
print("Addition :" ,array1 + Ones)
print("Substraction :" ,array1 - Ones)
print("Multiplication :" ,array1 * Ones)
print("Divide:" ,array1/Ones)

Addition : [[11.  8. 20.]]
Substraction : [[ 9.  6. 18.]]
Multiplication : [[10.  7. 19.]]
Divide: [[10.  7. 19.]]


In [51]:
print(array2),print("Shape :" ,array2.shape)

[[10.    7.   19.  ]
 [ 1.    2.    3.05]]
Shape : (2, 3)


(None, None)

In [52]:
print("Addition :\n" ,array2 + Ones)
print("Substraction: \n" ,array2 - Ones)
print("Multiplication: \n" ,array2 * Ones)
print("Divide:\n" ,array2/Ones)

Addition :
 [[11.    8.   20.  ]
 [ 2.    3.    4.05]]
Substraction: 
 [[ 9.    6.   18.  ]
 [ 0.    1.    2.05]]
Multiplication: 
 [[10.    7.   19.  ]
 [ 1.    2.    3.05]]
Divide:
 [[10.    7.   19.  ]
 [ 1.    2.    3.05]]


In [53]:
print(array3) ,print(array3.shape)

[[[10  7 19]
  [ 1  2  3]
  [20 55 90]]

 [[99 88 77]
  [37 54 29]
  [23 59 62]]]
(2, 3, 3)


(None, None)

In [54]:
print("Addition :\n" ,array2 + array3)
print("Substraction: \n" ,array2 - array3)
print("Multiplication: \n" ,array2 * array3)
print("Divide:" ,array2/array3)

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

#### Hmmmm?? Why we get an error ? We are just following the steps ..Is there any rules do we need to follow? Well Yes ! Read about Broadcasting arrays linked Below: In short the shape and dimesnions  of both arrays  is inappropriate to perfrom operations. 

#### 📚Resources : Broadcasting Arrays :- https://numpy.org/doc/stable/user/basics.broadcasting.html

General Broadcasting Rules
When operating on two arrays, NumPy compares their shapes element-wise. It starts with the trailing (i.e. rightmost) dimensions and works its way left. Two dimensions are compatible when

1. they are equal, or

2. one of them is 1

## 😤Lets Reshape Arrays to eliminate Errors and Lets us Run our cell

In [55]:
print(array2) ,print("Shape :",array2.shape) ,print("Dimension :" ,array2.ndim)

[[10.    7.   19.  ]
 [ 1.    2.    3.05]]
Shape : (2, 3)
Dimension : 2


(None, None, None)

In [56]:
array2_reshaped = array2.reshape(2,3,1)

In [57]:
print(array2_reshaped) ,print("Shape :",array2_reshaped.shape) ,print("Dimension :" ,array2_reshaped.ndim)

[[[10.  ]
  [ 7.  ]
  [19.  ]]

 [[ 1.  ]
  [ 2.  ]
  [ 3.05]]]
Shape : (2, 3, 1)
Dimension : 3


(None, None, None)

In [58]:
print(array3) ,print("Shape :",array3.shape) ,print("Dimension :" ,array3.ndim)

[[[10  7 19]
  [ 1  2  3]
  [20 55 90]]

 [[99 88 77]
  [37 54 29]
  [23 59 62]]]
Shape : (2, 3, 3)
Dimension : 3


(None, None, None)

In [59]:
array2_reshaped * array3

array([[[ 100.  ,   70.  ,  190.  ],
        [   7.  ,   14.  ,   21.  ],
        [ 380.  , 1045.  , 1710.  ]],

       [[  99.  ,   88.  ,   77.  ],
        [  74.  ,  108.  ,   58.  ],
        [  70.15,  179.95,  189.1 ]]])

## 🔥 Yipppppeeee... We have Done this... Thank you so much to help me..

### 🚀Try this : http://matrixmultiplication.xyz/

### 🚀Exercise : Try more Arithmatic operations with this arrays using Numpy function for math

## Aggregation :

#### 📚Resources : Aggregration :- https://www.tutorialgateway.org/python-numpy-aggregate-functions/

In [60]:
print(array1) ,print("Shape :",array1.shape) , print("Dimensions:", array1.ndim)

[10  7 19]
Shape : (3,)
Dimensions: 1


(None, None, None)

In [61]:
print("Sum of Elements in Array:", array1.sum())
print("Average of Elements in Array:", np.average(array1))
print("Product of Elements in Array:", np.prod(array1))
print("Minimum of Elements in Array:", np.min(array1))
print("Maximum of Elements in Array:", np.max(array1))
print("Median of Elements in Array:", np.median(array1))
print("Std deviation of Elements in Array:", np.std(array1))
print("Varianceof Elements in Array:", np.var(array1))

Sum of Elements in Array: 36
Average of Elements in Array: 12.0
Product of Elements in Array: 1330
Minimum of Elements in Array: 7
Maximum of Elements in Array: 19
Median of Elements in Array: 10.0
Std deviation of Elements in Array: 5.0990195135927845
Varianceof Elements in Array: 26.0


### Lets Try for 3 Dimension array

In [62]:
print(array3) ,print("Shape:",array3.shape) ,print("Dimensions:",array3.ndim)

[[[10  7 19]
  [ 1  2  3]
  [20 55 90]]

 [[99 88 77]
  [37 54 29]
  [23 59 62]]]
Shape: (2, 3, 3)
Dimensions: 3


(None, None, None)

In [63]:
print("Sum of Elements in Array:", array3.sum())
print("Average of Elements in Array:", np.average(array3))
print("Product of Elements in Array:", np.prod(array3))
print("Minimum of Elements in Array:", np.min(array3))
print("Maximum of Elements in Array:", np.max(array3))
print("Median of Elements in Array:", np.median(array3))
print("Std deviation of Elements in Array:", np.std(array3))
print("Varianceof Elements in Array:", np.var(array3))

Sum of Elements in Array: 735
Average of Elements in Array: 40.833333333333336
Product of Elements in Array: -1063574528
Minimum of Elements in Array: 1
Maximum of Elements in Array: 99
Median of Elements in Array: 33.0
Std deviation of Elements in Array: 32.05074102107469
Varianceof Elements in Array: 1027.25


# Transpose : Switch the axis

In [64]:
print(array1) ,print("Shape :",array1.shape) , print("Dimensions:", array1.ndim)

[10  7 19]
Shape : (3,)
Dimensions: 1


(None, None, None)

In [65]:
array1_transpose = array2.T

In [66]:
print(array1_transpose) ,print("Shape :",array1_transpose.shape) , print("Dimensions:", array1_transpose.ndim)

[[10.    1.  ]
 [ 7.    2.  ]
 [19.    3.05]]
Shape : (3, 2)
Dimensions: 2


(None, None, None)

## 📌Session 6 : Dot Product vs Element Wise 

#### 📚Resources :  Dot Product vs Element Wise :-https://www.mathwarehouse.com/algebra/matrix/multiply-matrix.php

In [67]:
np.random.seed(42)

mat1 = np.random.randint(low = 0 ,high = 10 ,size = (5,3))
mat2 = np.random.randint(low = 0 ,high = 10 ,size = (5,3))

In [68]:
print(mat1) , print("Shape :" ,mat1.shape) ,print("Dimensions :",mat1.ndim)

[[6 3 7]
 [4 6 9]
 [2 6 7]
 [4 3 7]
 [7 2 5]]
Shape : (5, 3)
Dimensions : 2


(None, None, None)

# Element Wise Product

In [69]:
ewp = mat1 * mat2

In [70]:
print(mat1 * mat2) , print("Shape:" ,ewp.shape) , print("Dimesnion :" ,ewp.ndim)

[[24  3 49]
 [20  6 36]
 [ 0 54 35]
 [32  0 63]
 [14 12 15]]
Shape: (5, 3)
Dimesnion : 2


(None, None, None)

# Dot Product

In [71]:
dp = np.dot(mat1 ,mat2)

ValueError: shapes (5,3) and (5,3) not aligned: 3 (dim 1) != 5 (dim 0)

#### Hmmmm?? Why we get an error ? We are just following the steps ..Is there any rules do we need to follow? Well Yes ! Read again about Broadcasting arrays linked Below: In short the shape and dimesnions  of both arrays  is inappropriate to perfrom operations. 

In [72]:
mat1_transpose = mat1.T

In [73]:
print(mat1_transpose) , print("Shape:" ,mat1_transpose.shape) , print("Dimesnion :" ,mat1_transpose.ndim)

[[6 4 2 4 7]
 [3 6 6 3 2]
 [7 9 7 7 5]]
Shape: (3, 5)
Dimesnion : 2


(None, None, None)

In [74]:
dp_new = np.dot(mat1_transpose,mat2)

In [75]:
print(dp_new) , print("Shape:" ,dp_new.shape) , print("Dimesnion :" ,dp_new.ndim)

[[ 90  70 125]
 [ 70  75 108]
 [139 109 198]]
Shape: (3, 3)
Dimesnion : 2


(None, None, None)

## 🔥 Congratulations we solved the problem  again !!!!!!!!!!!

## 📌Session 7 : Sorting Arrays

In [76]:
np.random.seed(42)

random = np.random.randint(20 ,size = (5,5) )
print(random)

[[ 6 19 14 10  7]
 [ 6 18 10 10  3]
 [ 7  2  1 11  5]
 [ 1  0 11 11 16]
 [ 9 15 14 14 18]]


In [77]:
random_sort = np.sort(random)
print(random_sort)

[[ 6  7 10 14 19]
 [ 3  6 10 10 18]
 [ 1  2  5  7 11]
 [ 0  1 11 11 16]
 [ 9 14 14 15 18]]


In [78]:

# It shows the indices of the random numbers that where it should be (position) after the sorting 

indices_of_sorted_randoms =np.argsort(random)
print(indices_of_sorted_randoms)

[[0 4 3 2 1]
 [4 0 2 3 1]
 [2 1 4 0 3]
 [1 0 2 3 4]
 [0 2 3 1 4]]


In [79]:
max_random_values_index = np.argmax(random ) # use axis = 0 : rows | 1 :colms 
print(max_random_values_index)

1


In [80]:
min_random_values_index = np.argmin(random)  # use axis = 0 : rows | 1 :colms 
print(min_random_values_index)

16


## 📌Session 8 : Turning Images into Numpy arrays ( Practical Example  )

In [81]:
# <img src = "images/panda.png"/> in markdown cell

<img src= "images/panda.png"/>

In [82]:
from matplotlib.image import imread

In [83]:
panda = imread("images/panda.png")

In [84]:
print(panda)

[[[0.05490196 0.10588235 0.06666667]
  [0.05490196 0.10588235 0.06666667]
  [0.05490196 0.10588235 0.06666667]
  ...
  [0.16470589 0.12941177 0.09411765]
  [0.16470589 0.12941177 0.09411765]
  [0.16470589 0.12941177 0.09411765]]

 [[0.05490196 0.10588235 0.06666667]
  [0.05490196 0.10588235 0.06666667]
  [0.05490196 0.10588235 0.06666667]
  ...
  [0.16470589 0.12941177 0.09411765]
  [0.16470589 0.12941177 0.09411765]
  [0.16470589 0.12941177 0.09411765]]

 [[0.05490196 0.10588235 0.06666667]
  [0.05490196 0.10588235 0.06666667]
  [0.05490196 0.10588235 0.06666667]
  ...
  [0.16470589 0.12941177 0.09411765]
  [0.16470589 0.12941177 0.09411765]
  [0.16470589 0.12941177 0.09411765]]

 ...

 [[0.13333334 0.07450981 0.05490196]
  [0.12156863 0.0627451  0.04313726]
  [0.10980392 0.05098039 0.03137255]
  ...
  [0.02745098 0.02745098 0.03529412]
  [0.02745098 0.02745098 0.03529412]
  [0.02745098 0.02745098 0.03529412]]

 [[0.13333334 0.07450981 0.05490196]
  [0.12156863 0.0627451  0.04313726]


In [85]:
print("Size :",panda.size)  # rows * cols * rgb 
print("Shape :" , panda.shape) 
print("Data type :",panda.dtype)
print("Dimension of array:" , panda.ndim)
print("Type of array :" ,type(panda))

Size : 24465000
Shape : (2330, 3500, 3)
Data type : float32
Dimension of array: 3
Type of array : <class 'numpy.ndarray'>


## 🚀 Exercise : Try it out for Car and Dog image

## 💻 Practical Implementation  : Nut Butter Store Sales (Optional) 

### Create Sales Amounts array

In [86]:
np.random.seed(42)

sales_amts = np.random.randint(20 ,size =(5,3))
print(sales_amts) ,print("Shape:",sales_amts.shape) ,print("Dimensions :",sales_amts.ndim)

[[ 6 19 14]
 [10  7  6]
 [18 10 10]
 [ 3  7  2]
 [ 1 11  5]]
Shape: (5, 3)
Dimensions : 2


(None, None, None)

### Create Pandas Dataframe

In [87]:
import pandas as pd

In [88]:
weekly_sales = pd.DataFrame(sales_amts , index=["Mon" ,"Tues" ,"Wed" ,"Thurs" ,"Fri"] 
                            ,columns= ["Almond Butter" ,"Peanut Butter" ,"Cashew Butter"]) 

In [89]:
print(weekly_sales)

       Almond Butter  Peanut Butter  Cashew Butter
Mon                6             19             14
Tues              10              7              6
Wed               18             10             10
Thurs              3              7              2
Fri                1             11              5


### Create Price array

In [90]:
prices = np.array([10,12,8])
print(prices) ,print("Shape :",prices.shape) , print("Dimension:",prices.ndim)

[10 12  8]
Shape : (3,)
Dimension: 1


(None, None, None)

### Create Pandas Dataframe for Prices

In [91]:
prices_df = pd.DataFrame(prices.reshape(1,3) , index=["Prices"] , columns= ["Almond Butter" ,"Peanut Butter" ,"Cashew Butter"])

In [92]:
print(prices_df)

        Almond Butter  Peanut Butter  Cashew Butter
Prices             10             12              8


## Total sales array 

In [93]:
total_sales = prices.dot(sales_amts.T)

In [94]:
print(total_sales) ,print("Shape :",total_sales.shape) , print("Dimension:",total_sales.ndim)

[400 232 380 130 182]
Shape : (5,)
Dimension: 1


(None, None, None)

## Merge daily sales and weekly sales dataframes

In [95]:
prices_df.shape , weekly_sales.shape

((1, 3), (5, 3))

In [96]:
daily_sales = prices_df.dot(weekly_sales.T)

In [97]:
daily_sales

Mon  Tues  Wed  Thurs  Fri
Prices  400   232  380    130  182

In [98]:
weekly_sales

Almond Butter  Peanut Butter  Cashew Butter
Mon                6             19             14
Tues              10              7              6
Wed               18             10             10
Thurs              3              7              2
Fri                1             11              5

In [99]:
weekly_sales["Total ($)"] = daily_sales.T

## Final Output

In [100]:
weekly_sales

Almond Butter  Peanut Butter  Cashew Butter  Total ($)
Mon                6             19             14        400
Tues              10              7              6        232
Wed               18             10             10        380
Thurs              3              7              2        130
Fri                1             11              5        182

## Congratulations ..You are 🐐 of Numpy now.. I apprepreciate your efforts and Learning ..